### ISSUE TITLE
Cursor position drift when change font-size by fontsizeselect

### ISSUE THREAD

**Issue by shikelong** [HurricaneJames/react-tinymce-input#11]
![tinymcebug1](https://cloud.githubusercontent.com/assets/4499997/22179548/17ad53d2-e092-11e6-9fd8-a24d74ee321f.gif)

Seem change font-size will cause the cursor'is position reset.

Regards.

**Comment by difelice** [comment]
I think this happens as soon as a new tag is added to the source.

**Comment by difelice** [comment]
Try to add `ignoreUpdatesWhenFocused`:
```js
<TinyMCEInput
  ignoreUpdatesWhenFocused
  ...
/>
```
