### ISSUE TITLE
React 15.5 deprecation warnings

### ISSUE THREAD

**Issue by alysov** [HurricaneJames/react-tinymce-input#17]
From [React 15.5's release notes](https://github.com/facebook/react/releases/tag/v15.5.0):

> * Added a deprecation warning for React.createClass. Points users to create-react-class instead.
> * Added a deprecation warning for React.PropTypes. Points users to prop-types instead.

This results in projects that are using that version of React to have warnings due to react-tinymce-input.
I propose going with React's recommendations, but I don't know how that will affect the backwards compatibility of this project, if you really want to maintain compatibility [all the way back to React 13](https://github.com/HurricaneJames/react-tinymce-input/blob/master/package.json#L44).

**Comment by HurricaneJames** [comment]
thanks, merged and published as v2.0
