### ISSUE TITLE
onClick event && placeholder

### ISSUE THREAD

**Issue by mikecann** [HurricaneJames/react-tinymce-input#5]
Hey,

Firstly, great work on this, I tried the other react tinymce but I agree with you, it was too low level and didn't play nice when you wanted react to update the content.

Your implementation is perfect except two things.. 

1) I would love to get an on-click event so I can auto-fill the content when clicked. 
2) I really would love to get a placeholder on the text area. I managed to get it working with this plugin "https://github.com/mohan999/tinymce-placeholder" so if you could just pass through a "placeholder" prop to the textarea that would be great.

Thanks for the awesome work!
Mike

**Comment by HurricaneJames** [comment]
I think I have an idea on how to fix this. I will work on it over the weekend. Sorry for the delay, I spent the last month moving from east-coast to west and changing jobs.

**Comment by mikecann** [comment]
Hey no worries, I really appreciate all your hard work!

**Comment by HurricaneJames** [comment]
I just published v 1.2.0. It has a `textareaProps` prop to passthrough any props directly to the textarea. It also has an `onClick` event handler. Additionally, I added an `otherEventHandlers` prop that takes an object/Map that maps event names (case sensitive) to callback functions. Hope that handles everything you needed.

**Comment by mikecann** [comment]
Awesome! Thats perfect, ill be checking it out soon for sure!

On 12 February 2016 at 13:17, James Burnett notifications@github.com
wrote:

> I just published v 1.2.0. It has a textareaProps prop to passthrough any
> props directly to the textarea. It also has an onClick event handler.
> Additionally, I added an otherEventHandlers prop that takes an object/Map
> that maps event names (case sensitive) to callback functions. Hope that
> handles everything you needed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HurricaneJames/react-tinymce-input/issues/5#issuecomment-183182999
> .

## 

_Mike Cann_
http://www.mikecann.co.uk/
@mikeysee http://www.twitter.com/mikeysee
